### ISSUE TITLE
Streak broken?

### ISSUE THREAD

**Issue by ljharb** [Naramsim/GithubOriginalStreak#88]
As of today or yesterday, "current streak" seems to only be calculating based on the visible squares.

For example, when i go to https://github.com/ljharb?tab=overview&from=2021-03-01&to=2021-03-25, it shows me a current streak of "0 days"; when i go to https://github.com/ljharb, it shows me a current streak of 369 days. Neither is correct.

**Comment by Naramsim** [comment]
Hi @ljharb, the streak is calculated backward starting from the `rightest` day. In your first example, the rightest day is Dec 31 2021, which isn't yet happened. So I guess it's normal we calculate 0 days for that example.

Regarding your second example, I see your current streak equal to 109 days. Take a look below:

![ljharb](https://user-images.githubusercontent.com/8996268/112546638-f55e5b80-8db9-11eb-8871-3b50dfd9d758.PNG)

On Dec 6 I don't have any contribution. On your calendar do you have contributions for Dec 6? Are those private?

**Comment by Naramsim** [comment]
If you had a full green calendar, then for you, @ljharb, the longest streak would have been calculated starting from 2020-03-22.

Does it seem right?

**Comment by Naramsim** [comment]
Anyway, I think that the ability Github implemented about checking past years and thus rendering the calendar, broke the extension in case someone had a very long streak.

**Comment by Naramsim** [comment]
Yeah, I thought about it. So, if you request through the UI a different time period && you had a full streak. Then your full-streak can be broken if in the new rendered calendar there are 'holes'. So to fix this behavior I need to only update our database (a Github gist) when the default view is shown to the user. That is when the query string of the URL doesn't contain any `to` or `from`. 

I'll try to fix it as soon as possible. But I'm doing so many other things... I hope I can @ljharb

**Comment by ljharb** [comment]
Hmm - I definitely have contributions on that day, a PR review - on mine, the square shows filled in. Github does sometimes blank out days temporarily, i have no idea why.

Similarly, I have contributions on 2020-03-21 (also 2 PR reviews). My streak goes back to 2014.

Perhaps these anomalies are just on github's side.

**Comment by ljharb** [comment]
Thanks!

Contributions in the past can happen any time, but it seems reasonable to assume that anything more than a year old is "frozen", or at least cached aggressively.

**Comment by Naramsim** [comment]
Nono, those anomalies are on Github and they were reflected in our database. 

Can you please write your starting date down? If you don't remember I have to dig it up, but it's possible. Anyway, up until Github doesn't show that square green, I can't update your longest streak.

**Comment by ljharb** [comment]
it's 2014-04-16.

**Comment by g-harel** [comment]
May be a separate thing, but I'm also seeing a much shorter streak than before. It's suspiciously stopping almost exactly a year ago on my profile.

**Comment by ljharb** [comment]
Today, a few days later, it's still saying my streak ends almost exactly a year ago. The implication is that it's not counting beyond a year anymore.

**Comment by Naramsim** [comment]
For you @ljharb this is the case. Because you have a hole in the calendar

**Comment by ljharb** [comment]
@Naramsim a hole that moves one day every day? Now it says it goes back to the 29th, and the (incorrect) hole you saw was on the 21st.

**Comment by spences10** [comment]
Same here, looks like it's only doing it for the last 366 days?
![image](https://user-images.githubusercontent.com/234708/114587558-b1a29780-9c7d-11eb-81e3-bb05261a06b4.png)

**Comment by Naramsim** [comment]
Hi @spences10 Yesterday I released on Chrome and FF a _potential_ fix for the bug. In the meantime, I reverted your old start contribution date to what it was.

I believe that there are still browsers that are using the old version of this extension, and when one loads your profile it could change the starting date back to Apr 2020. I guess we need to wait a bit and see if the error still happens.

**Comment by spences10** [comment]
I'm using MS Edge, shall I try uninstall and reinstall?

**Comment by spences10** [comment]
I just installed the Chrome version and it's working now 😊
![image](https://user-images.githubusercontent.com/234708/114605564-1ec02800-9c92-11eb-9d7c-89b0185c9027.png)

**Comment by ljharb** [comment]
@Naramsim how do i ensure the extension is updated? i'm still seeing 366 days back (i have v1.14.14)

**Comment by Naramsim** [comment]
@ljharb I updated your starting date but as soon as I updated it, it got reverted. 

I'll try tomorrow. 1.14.14 is the latest version.

Also, your streak will only display for not logged-in users. I noted that the 'hole' is present if you are logged in and isn't any more present if you log out. Github itself has probably a bug in building the calendar.

**Comment by Naramsim** [comment]
> I'm using MS Edge, shall I try uninstall and reinstall?

Hi @spences10, in Edge how do you install this extension? Is there a marketplace?

**Comment by ljharb** [comment]
@Naramsim in my specific case, i only ever view my streak as a logged-out user, for the exact reason that i want to see how others see it :-) github definitely has many such bugs at times.

Thanks, I'll try again tomorrow. How can i ensure that I have the newest version of the extension?

**Comment by Naramsim** [comment]
Chrome, in theory, auto-updates everything as soon as possible.

**Comment by ljharb** [comment]
@Naramsim any chance you could try resetting my start date now? :-)

**Comment by Naramsim** [comment]
@ljharb, I rolled out a new version, fixing the issue also for your profile.

I'd wait 1 or 2 days, sorry.

**Comment by ljharb** [comment]
Thanks! I’ll check in 48 hours, and I’ll try not to refresh that page in chrome until then :-)

**Comment by Naramsim** [comment]
Well, the chrome extension is already deployed. `.15` is the newer version, you can check if it's installed by going to the 3-dots menu and select more tools -> extensions.

**Comment by ljharb** [comment]
I'm on that version - does that mean it's safe to refresh?

**Comment by Naramsim** [comment]
yes hahah

**Comment by ljharb** [comment]
yayyyyyy thank you!
<img width="753" alt="Screen Shot 2021-04-16 at 12 53 01 PM" src="https://user-images.githubusercontent.com/45469/115077339-bbf9a700-9eb2-11eb-99df-3cbb780dec14.png">

**Comment by ljharb** [comment]
@Naramsim this seems to have happened again - it thinks i have no contributions on 2022.01.08, but github currently shows me having 19.

**Comment by Naramsim** [comment]
yes, we are aware of the issue over here: https://github.com/Naramsim/GithubOriginalStreak/issues/89
